# Form implementation generated from reading ui file '.\ui\main.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(477, 702)
        Form.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"border-radius:8px;\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.welcome_page = QtWidgets.QWidget()
        self.welcome_page.setObjectName("welcome_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.welcome_page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(parent=self.welcome_page)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../sources/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(300, 300))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(parent=self.welcome_page)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.open_new_accont_btn = QtWidgets.QPushButton(parent=self.widget_2)
        self.open_new_accont_btn.setMinimumSize(QtCore.QSize(200, 50))
        self.open_new_accont_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.open_new_accont_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(1, 27, 51);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"padding:0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.open_new_accont_btn.setObjectName("open_new_accont_btn")
        self.verticalLayout_3.addWidget(self.open_new_accont_btn)
        self.opne_login_btn = QtWidgets.QPushButton(parent=self.widget_2)
        self.opne_login_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.opne_login_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.opne_login_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(1, 27, 51);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"padding:0px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.opne_login_btn.setObjectName("opne_login_btn")
        self.verticalLayout_3.addWidget(self.opne_login_btn)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedWidget.addWidget(self.welcome_page)
        self.create_account = QtWidgets.QWidget()
        self.create_account.setObjectName("create_account")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.create_account)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_3 = QtWidgets.QWidget(parent=self.create_account)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget_3)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.widget_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.widget_11 = QtWidgets.QWidget(parent=self.create_account)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_11.sizePolicy().hasHeightForWidth())
        self.widget_11.setSizePolicy(sizePolicy)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_4.addWidget(self.widget_11)
        self.widget_4 = QtWidgets.QWidget(parent=self.create_account)
        self.widget_4.setStyleSheet("background-color: rgb(225, 225, 226)")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_7.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_3.setMinimumSize(QtCore.QSize(121, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.name = QtWidgets.QLineEdit(parent=self.widget_7)
        self.name.setMinimumSize(QtCore.QSize(220, 35))
        self.name.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.name.setPlaceholderText("")
        self.name.setObjectName("name")
        self.horizontalLayout_5.addWidget(self.name)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_6.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_2.setMinimumSize(QtCore.QSize(121, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.user = QtWidgets.QLineEdit(parent=self.widget_6)
        self.user.setMinimumSize(QtCore.QSize(220, 35))
        self.user.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.user.setPlaceholderText("")
        self.user.setObjectName("user")
        self.horizontalLayout_4.addWidget(self.user)
        self.verticalLayout_5.addWidget(self.widget_6)
        self.widget_10 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_10.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_8.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_10)
        self.label_6.setMinimumSize(QtCore.QSize(121, 0))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.email = QtWidgets.QLineEdit(parent=self.widget_10)
        self.email.setMinimumSize(QtCore.QSize(220, 35))
        self.email.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.email.setPlaceholderText("")
        self.email.setObjectName("email")
        self.horizontalLayout_8.addWidget(self.email)
        self.verticalLayout_5.addWidget(self.widget_10)
        self.widget_9 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_9.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_9.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_9.setObjectName("widget_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
        self.horizontalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_9)
        self.label_5.setMinimumSize(QtCore.QSize(121, 0))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.password = QtWidgets.QLineEdit(parent=self.widget_9)
        self.password.setMinimumSize(QtCore.QSize(220, 35))
        self.password.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.password.setPlaceholderText("")
        self.password.setObjectName("password")
        self.horizontalLayout_7.addWidget(self.password)
        self.verticalLayout_5.addWidget(self.widget_9)
        self.widget_8 = QtWidgets.QWidget(parent=self.widget_4)
        self.widget_8.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_8.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(parent=self.widget_8)
        self.label_4.setMinimumSize(QtCore.QSize(101, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.password_2 = QtWidgets.QLineEdit(parent=self.widget_8)
        self.password_2.setMinimumSize(QtCore.QSize(220, 35))
        self.password_2.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.password_2.setPlaceholderText("")
        self.password_2.setObjectName("password_2")
        self.horizontalLayout_6.addWidget(self.password_2)
        self.verticalLayout_5.addWidget(self.widget_8)
        self.verticalLayout_4.addWidget(self.widget_4)
        self.widget_12 = QtWidgets.QWidget(parent=self.create_account)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_4.addWidget(self.widget_12)
        self.widget_5 = QtWidgets.QWidget(parent=self.create_account)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.save = QtWidgets.QPushButton(parent=self.widget_5)
        self.save.setMinimumSize(QtCore.QSize(250, 40))
        self.save.setMaximumSize(QtCore.QSize(250, 40))
        self.save.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 73, 125);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.save.setObjectName("save")
        self.verticalLayout_6.addWidget(self.save)
        self.widget_13 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back = QtWidgets.QPushButton(parent=self.widget_13)
        self.back.setMinimumSize(QtCore.QSize(100, 30))
        self.back.setMaximumSize(QtCore.QSize(130, 16777215))
        self.back.setStyleSheet("QPushButton {\n"
"    background-color: rgb(249, 68, 73);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(175, 47, 51);\n"
"}\n"
"")
        self.back.setObjectName("back")
        self.horizontalLayout_3.addWidget(self.back)
        self.verticalLayout_6.addWidget(self.widget_13)
        self.verticalLayout_4.addWidget(self.widget_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedWidget.addWidget(self.create_account)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.login_page)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_21 = QtWidgets.QWidget(parent=self.login_page)
        self.widget_21.setObjectName("widget_21")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_21)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(parent=self.widget_21)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.verticalLayout_9.addWidget(self.widget_21)
        self.widget_14 = QtWidgets.QWidget(parent=self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_14.sizePolicy().hasHeightForWidth())
        self.widget_14.setSizePolicy(sizePolicy)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_9.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(parent=self.login_page)
        self.widget_15.setStyleSheet("background-color: rgb(225, 225, 226)")
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_17 = QtWidgets.QWidget(parent=self.widget_15)
        self.widget_17.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_17.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_17)
        self.label_8.setMinimumSize(QtCore.QSize(121, 0))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.user_2 = QtWidgets.QLineEdit(parent=self.widget_17)
        self.user_2.setMinimumSize(QtCore.QSize(220, 35))
        self.user_2.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.user_2.setPlaceholderText("")
        self.user_2.setObjectName("user_2")
        self.horizontalLayout_10.addWidget(self.user_2)
        self.verticalLayout_7.addWidget(self.widget_17)
        self.widget_19 = QtWidgets.QWidget(parent=self.widget_15)
        self.widget_19.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_19.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_12.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtWidgets.QLabel(parent=self.widget_19)
        self.label_10.setMinimumSize(QtCore.QSize(121, 0))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.password_3 = QtWidgets.QLineEdit(parent=self.widget_19)
        self.password_3.setMinimumSize(QtCore.QSize(220, 35))
        self.password_3.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.password_3.setPlaceholderText("")
        self.password_3.setObjectName("password_3")
        self.horizontalLayout_12.addWidget(self.password_3)
        self.verticalLayout_7.addWidget(self.widget_19)
        self.verticalLayout_9.addWidget(self.widget_15)
        self.widget_24 = QtWidgets.QWidget(parent=self.login_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_24.sizePolicy().hasHeightForWidth())
        self.widget_24.setSizePolicy(sizePolicy)
        self.widget_24.setObjectName("widget_24")
        self.verticalLayout_9.addWidget(self.widget_24)
        self.widget_22 = QtWidgets.QWidget(parent=self.login_page)
        self.widget_22.setObjectName("widget_22")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_22)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.login = QtWidgets.QPushButton(parent=self.widget_22)
        self.login.setMinimumSize(QtCore.QSize(250, 40))
        self.login.setMaximumSize(QtCore.QSize(250, 40))
        self.login.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 73, 125);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.login.setObjectName("login")
        self.verticalLayout_8.addWidget(self.login)
        self.widget_23 = QtWidgets.QWidget(parent=self.widget_22)
        self.widget_23.setObjectName("widget_23")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_23)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.back_2 = QtWidgets.QPushButton(parent=self.widget_23)
        self.back_2.setMinimumSize(QtCore.QSize(100, 30))
        self.back_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.back_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(249, 68, 73);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(175, 47, 51);\n"
"}\n"
"")
        self.back_2.setObjectName("back_2")
        self.horizontalLayout_15.addWidget(self.back_2)
        self.verticalLayout_8.addWidget(self.widget_23)
        self.verticalLayout_9.addWidget(self.widget_22, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedWidget.addWidget(self.login_page)
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.home_page)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_16 = QtWidgets.QWidget(parent=self.home_page)
        self.widget_16.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_16.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_9.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_16)
        self.pushButton_2.setMinimumSize(QtCore.QSize(35, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\ui\\../sources/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.widget_25 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_25.setObjectName("widget_25")
        self.horizontalLayout_9.addWidget(self.widget_25)
        self.label_11 = QtWidgets.QLabel(parent=self.widget_16)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.widget_26 = QtWidgets.QWidget(parent=self.widget_16)
        self.widget_26.setObjectName("widget_26")
        self.horizontalLayout_9.addWidget(self.widget_26)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.widget_16)
        self.pushButton_5.setMinimumSize(QtCore.QSize(35, 0))
        self.pushButton_5.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_5.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\ui\\../sources/config-svgrepo-com.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_5.setIcon(icon2)
        self.pushButton_5.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.verticalLayout_10.addWidget(self.widget_16)
        self.widget_18 = QtWidgets.QWidget(parent=self.home_page)
        self.widget_18.setStyleSheet("background-color: rgb(238, 238, 239);")
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_20 = QtWidgets.QWidget(parent=self.widget_18)
        self.widget_20.setMinimumSize(QtCore.QSize(0, 40))
        self.widget_20.setObjectName("widget_20")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.widget_20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.search = QtWidgets.QLineEdit(parent=self.widget_20)
        self.search.setMinimumSize(QtCore.QSize(220, 35))
        self.search.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.search.setPlaceholderText("")
        self.search.setObjectName("search")
        self.horizontalLayout_11.addWidget(self.search)
        self.search_btn = QtWidgets.QPushButton(parent=self.widget_20)
        self.search_btn.setMinimumSize(QtCore.QSize(130, 35))
        self.search_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.search_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 73, 125);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_11.addWidget(self.search_btn)
        self.verticalLayout_11.addWidget(self.widget_20)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget_18)
        self.scrollArea.setStyleSheet("\n"
"background-color: rgb(222, 222, 223);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 455, 566))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.verticalLayout_10.addWidget(self.widget_18)
        self.stackedWidget.addWidget(self.home_page)
        self.chat_page = QtWidgets.QWidget()
        self.chat_page.setObjectName("chat_page")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.chat_page)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 3)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.widget_27 = QtWidgets.QWidget(parent=self.chat_page)
        self.widget_27.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_27.setObjectName("widget_27")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_27)
        self.horizontalLayout_13.setContentsMargins(9, 3, -1, 3)
        self.horizontalLayout_13.setSpacing(3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.back_3 = QtWidgets.QPushButton(parent=self.widget_27)
        self.back_3.setMinimumSize(QtCore.QSize(40, 40))
        self.back_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.back_3.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 73, 125);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.back_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\ui\\../sources/back-svgrepo-com.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_3.setIcon(icon3)
        self.back_3.setIconSize(QtCore.QSize(30, 30))
        self.back_3.setObjectName("back_3")
        self.horizontalLayout_13.addWidget(self.back_3)
        self.frame = QtWidgets.QFrame(parent=self.widget_27)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_13.addWidget(self.frame)
        self.label_13 = QtWidgets.QLabel(parent=self.widget_27)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_13.addWidget(self.label_13)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_27)
        self.pushButton_3.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\ui\\../sources/profile-circle-svgrepo-com.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon4)
        self.pushButton_3.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_13.addWidget(self.pushButton_3)
        self.verticalLayout_12.addWidget(self.widget_27)
        self.widget_28 = QtWidgets.QWidget(parent=self.chat_page)
        self.widget_28.setObjectName("widget_28")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_28)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_30 = QtWidgets.QWidget(parent=self.widget_28)
        self.widget_30.setStyleSheet("    background-color: rgb(222, 222, 223);")
        self.widget_30.setObjectName("widget_30")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_30)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.widget_30)
        self.scrollArea_2.setStyleSheet("\n"
"\n"
"    QScrollBar:vertical {\n"
"        background: #f0f0f0;\n"
"        width: 12px;\n"
"        margin: 5px 0 5px 0;\n"
"        border: none;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical {\n"
"        background: #c4c4c4;\n"
"        min-height: 30px;\n"
"        border-radius: 6px;\n"
"    }\n"
"\n"
"    QScrollBar::handle:vertical:hover {\n"
"        background: #a0a0a0;\n"
"    }\n"
"\n"
"    QScrollBar::add-line:vertical,\n"
"    QScrollBar::sub-line:vertical {\n"
"        height: 0px;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"\n"
"    QScrollBar::add-page:vertical,\n"
"    QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 433, 564))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_14.addWidget(self.scrollArea_2)
        self.verticalLayout_13.addWidget(self.widget_30)
        self.verticalLayout_12.addWidget(self.widget_28)
        self.widget_29 = QtWidgets.QWidget(parent=self.chat_page)
        self.widget_29.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_29.setObjectName("widget_29")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_29)
        self.horizontalLayout_16.setContentsMargins(-1, 3, 6, 3)
        self.horizontalLayout_16.setSpacing(3)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.message_input = QtWidgets.QLineEdit(parent=self.widget_29)
        self.message_input.setMinimumSize(QtCore.QSize(220, 35))
        self.message_input.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.message_input.setPlaceholderText("")
        self.message_input.setObjectName("message_input")
        self.horizontalLayout_16.addWidget(self.message_input)
        self.send = QtWidgets.QPushButton(parent=self.widget_29)
        self.send.setMinimumSize(QtCore.QSize(60, 35))
        self.send.setMaximumSize(QtCore.QSize(60, 16777215))
        self.send.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 73, 125);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.send.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\ui\\../sources/send-svgrepo-com.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.send.setIcon(icon5)
        self.send.setIconSize(QtCore.QSize(30, 30))
        self.send.setObjectName("send")
        self.horizontalLayout_16.addWidget(self.send)
        self.verticalLayout_12.addWidget(self.widget_29)
        self.stackedWidget.addWidget(self.chat_page)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.widget_33 = QtWidgets.QWidget(parent=self.page)
        self.widget_33.setObjectName("widget_33")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_33)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_33)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_18.addWidget(self.label_7)
        self.verticalLayout_17.addWidget(self.widget_33)
        self.widget_34 = QtWidgets.QWidget(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_34.sizePolicy().hasHeightForWidth())
        self.widget_34.setSizePolicy(sizePolicy)
        self.widget_34.setObjectName("widget_34")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_34)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.widget_34)
        self.pushButton_4.setText("")
        self.pushButton_4.setIcon(icon4)
        self.pushButton_4.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_18.addWidget(self.pushButton_4)
        self.verticalLayout_17.addWidget(self.widget_34)
        self.widget_35 = QtWidgets.QWidget(parent=self.page)
        self.widget_35.setStyleSheet("background-color: rgb(225, 225, 226)")
        self.widget_35.setObjectName("widget_35")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_35)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_36 = QtWidgets.QWidget(parent=self.widget_35)
        self.widget_36.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_36.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_36.setObjectName("widget_36")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_36)
        self.horizontalLayout_19.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_36)
        self.label_9.setMinimumSize(QtCore.QSize(121, 0))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_19.addWidget(self.label_9)
        self.name_2 = QtWidgets.QLineEdit(parent=self.widget_36)
        self.name_2.setMinimumSize(QtCore.QSize(220, 35))
        self.name_2.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.name_2.setPlaceholderText("")
        self.name_2.setObjectName("name_2")
        self.horizontalLayout_19.addWidget(self.name_2)
        self.verticalLayout_16.addWidget(self.widget_36)
        self.widget_37 = QtWidgets.QWidget(parent=self.widget_35)
        self.widget_37.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_37.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_37.setObjectName("widget_37")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.widget_37)
        self.horizontalLayout_20.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_14 = QtWidgets.QLabel(parent=self.widget_37)
        self.label_14.setMinimumSize(QtCore.QSize(121, 0))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_20.addWidget(self.label_14)
        self.user_3 = QtWidgets.QLineEdit(parent=self.widget_37)
        self.user_3.setMinimumSize(QtCore.QSize(220, 35))
        self.user_3.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.user_3.setPlaceholderText("")
        self.user_3.setObjectName("user_3")
        self.horizontalLayout_20.addWidget(self.user_3)
        self.verticalLayout_16.addWidget(self.widget_37)
        self.widget_38 = QtWidgets.QWidget(parent=self.widget_35)
        self.widget_38.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_38.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_38.setObjectName("widget_38")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.widget_38)
        self.horizontalLayout_21.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_38)
        self.label_15.setMinimumSize(QtCore.QSize(121, 0))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_21.addWidget(self.label_15)
        self.email_2 = QtWidgets.QLineEdit(parent=self.widget_38)
        self.email_2.setMinimumSize(QtCore.QSize(220, 35))
        self.email_2.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.email_2.setPlaceholderText("")
        self.email_2.setObjectName("email_2")
        self.horizontalLayout_21.addWidget(self.email_2)
        self.verticalLayout_16.addWidget(self.widget_38)
        self.widget_39 = QtWidgets.QWidget(parent=self.widget_35)
        self.widget_39.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_39.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_39.setObjectName("widget_39")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.widget_39)
        self.horizontalLayout_22.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_39)
        self.label_16.setMinimumSize(QtCore.QSize(121, 0))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_22.addWidget(self.label_16)
        self.password_4 = QtWidgets.QLineEdit(parent=self.widget_39)
        self.password_4.setMinimumSize(QtCore.QSize(220, 35))
        self.password_4.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.password_4.setPlaceholderText("")
        self.password_4.setObjectName("password_4")
        self.horizontalLayout_22.addWidget(self.password_4)
        self.verticalLayout_16.addWidget(self.widget_39)
        self.widget_40 = QtWidgets.QWidget(parent=self.widget_35)
        self.widget_40.setMinimumSize(QtCore.QSize(0, 41))
        self.widget_40.setStyleSheet("background-color: rgb(238, 238, 239);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.widget_40.setObjectName("widget_40")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.widget_40)
        self.horizontalLayout_23.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_17 = QtWidgets.QLabel(parent=self.widget_40)
        self.label_17.setMinimumSize(QtCore.QSize(101, 0))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_23.addWidget(self.label_17)
        self.password_5 = QtWidgets.QLineEdit(parent=self.widget_40)
        self.password_5.setMinimumSize(QtCore.QSize(220, 35))
        self.password_5.setStyleSheet("background-color: rgb(222, 222, 223);\n"
"border-radius:8px;\n"
"font-size:14px;\n"
"padding-left:8px;\n"
"color:rgb(31, 73, 125)")
        self.password_5.setPlaceholderText("")
        self.password_5.setObjectName("password_5")
        self.horizontalLayout_23.addWidget(self.password_5)
        self.verticalLayout_16.addWidget(self.widget_40)
        self.verticalLayout_17.addWidget(self.widget_35)
        self.widget_41 = QtWidgets.QWidget(parent=self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_41.sizePolicy().hasHeightForWidth())
        self.widget_41.setSizePolicy(sizePolicy)
        self.widget_41.setObjectName("widget_41")
        self.verticalLayout_17.addWidget(self.widget_41)
        self.widget_31 = QtWidgets.QWidget(parent=self.page)
        self.widget_31.setObjectName("widget_31")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_31)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.save_2 = QtWidgets.QPushButton(parent=self.widget_31)
        self.save_2.setMinimumSize(QtCore.QSize(250, 40))
        self.save_2.setMaximumSize(QtCore.QSize(250, 40))
        self.save_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(31, 73, 125);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(18, 115, 176);\n"
"}\n"
"")
        self.save_2.setObjectName("save_2")
        self.verticalLayout_15.addWidget(self.save_2)
        self.widget_32 = QtWidgets.QWidget(parent=self.widget_31)
        self.widget_32.setObjectName("widget_32")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_32)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.back_4 = QtWidgets.QPushButton(parent=self.widget_32)
        self.back_4.setMinimumSize(QtCore.QSize(100, 30))
        self.back_4.setMaximumSize(QtCore.QSize(130, 16777215))
        self.back_4.setStyleSheet("QPushButton {\n"
"    background-color: rgb(249, 68, 73);\n"
"    border-radius: 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 16px;      /* tamanho da fonte */\n"
"    font-weight: bold;    /* deixa a fonte mais grossa */\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(175, 47, 51);\n"
"}\n"
"")
        self.back_4.setObjectName("back_4")
        self.horizontalLayout_17.addWidget(self.back_4)
        self.verticalLayout_15.addWidget(self.widget_32)
        self.verticalLayout_17.addWidget(self.widget_31, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.stackedWidget.addWidget(self.page)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.open_new_accont_btn.setText(_translate("Form", "CREATE ACCOUNT"))
        self.opne_login_btn.setText(_translate("Form", "LOGIN"))
        self.label.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#00165e;\">CREATE NEW ACCOUNT</span></p></body></html>"))
        self.label_3.setText(_translate("Form", "Name"))
        self.label_2.setText(_translate("Form", "User"))
        self.label_6.setText(_translate("Form", "Email"))
        self.label_5.setText(_translate("Form", "Password"))
        self.label_4.setText(_translate("Form", "Repeat Password"))
        self.save.setText(_translate("Form", "Salvar"))
        self.back.setText(_translate("Form", "Voltar"))
        self.label_12.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#00165e;\">LOGIN</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "User"))
        self.label_10.setText(_translate("Form", "Password"))
        self.login.setText(_translate("Form", "LOGIN"))
        self.back_2.setText(_translate("Form", "Voltar"))
        self.label_11.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#00165e;\">SECURE CHAT</span></p></body></html>"))
        self.search_btn.setText(_translate("Form", "BUSCAR"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#00165e;\">#USER_NAME</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; color:#00165e;\">MY ACCOUNT</span></p></body></html>"))
        self.label_9.setText(_translate("Form", "Name"))
        self.label_14.setText(_translate("Form", "User"))
        self.label_15.setText(_translate("Form", "Email"))
        self.label_16.setText(_translate("Form", "Password"))
        self.label_17.setText(_translate("Form", "Repeat Password"))
        self.save_2.setText(_translate("Form", "Salvar"))
        self.back_4.setText(_translate("Form", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
